README.md
=> Facu lopez dev

api/src/data/productos.json, api/src/models/Favoritos.js, api/src/models/Products.js, api/src/models/Reviews.js, api/src/models/Users.js
1- Creación de productos.json con 10 tablas de snowboard 2-Creacion de modelos [ Favoritos, Products, Reviews, Users
// Faltan realizar relación de los modelos y sus rutas
=> Creaciones

api/index.js, api/src/controllers/accessoriesControlles.js, api/src/controllers/loadData.js, api/src/db.js, api/src/routes/accesoriesRouter.js, api/src/routes/index.js
en teoria ya haciendo un npm i  + npm start ya se guardarian a la base de datos creadas en el servidor local
=> Acomodando el Load Data y el Bulkcreate

api/src/controllers/accessoriesControlles.js, api/src/data/accessories.json, api/src/data/boards.json, api/src/data/boots.json, api/src/data/jackets.json, api/src/data/pants.json, api/src/data/tShirts.json, api/src/routes/accesoriesRouter.js
Se modifico lso Jsons por motivo de que al tener un ID colocado manualmente creaba conflicto con el POST para cuando se le queria asignar un nuevo numero de ID, ya que este comenzaba en 1 y al estar ese ya creado en el Json generaba error..
=> acomodando Jsons y siguiendo con accessoriesControllers

client/src/App.js
=> app identado

client/src/App.js, client/src/components/Home/Home.jsx
=> route Home

api/src/app.js, api/src/controllers/tShirtsControllers.js, api/src/routes/index.js, api/src/routes/tShirtsRouter.js
Se hizo tShirtsController / Routes ..
=> Dev facu lopez

client/src/App.js, client/src/components/SearchBar/SearchBar.jsx, client/src/components/tiendaCategorias/Tienda.jsx, client/src/data/categorias.js, client/src/data/marcas.js
- productos destacados
- categorias (ver imagen de referencia)
- banner con ofertas
- nuestras marcas ( ver referencia)
=> pagina/ruta -> tienda

api/src/controllers/productsControllers.js, api/src/routes/productsRouter.js
Filter by Brand and Category DONE! Keep pushing!'
=> Facu gomez dev

client/src/App.js, client/src/components/CardBoard/CardBoard.jsx, client/src/components/CardBoots/CardBoots.css, client/src/components/CardBoots/CardBoots.jsx, client/src/components/CardJackets/CardJackets.css, client/src/components/CardJackets/CardJackets.jsx, client/src/components/CardPants/CardPants.css, client/src/components/CardPants/CardPants.jsx, client/src/components/CardTshirts/CardTshirts.css, client/src/components/CardTshirts/CardTshirts.jsx, client/src/components/Header/Header.css, client/src/components/Header/Header.jsx, client/src/components/Home/Home.jsx, client/src/components/SearchBar/SearchBar.css, client/src/components/SearchBar/SearchBar.jsx
arregle en estilos el header y la seachbar si se puede mejorar mejor/ chatbot en todas las paginas
=> hice las cards de los productos en generan, mejorar la info que queremos mostrar

client/src/components/tiendaCategorias/categorias/Categorias.jsx
=> tienda 2.0

client/src/components/Home/Home.css
=> gran cambio by pauli

client/src/components/Header/Header.jsx, client/src/components/tiendaCategorias/destacados/Destacados.jsx, client/src/components/tiendaCategorias/marcas/style.css
- Cambio en algunos estilos
- Cada Card de los productos destacados tiene el link para el detalle
=> estilos y destacados

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Header/Header.jsx, client/src/components/Login/Login.jsx, client/src/components/Logout/Logout.jsx, client/src/components/Profile/Profile.css, client/src/components/Profile/Profile.jsx, client/src/index.js
listo Auth0 para usar de forma local
=> components Login/Logout/Profile

api/package-lock.json, api/package.json, api/src/controllers/productsControllers.js
se agrega cloudinary en el post de products, cada imagen que se envie al formulario se guarda directamente en cloudinary en su respectiva carpeta de category
=> Cloudinary

client/src/App.js, client/src/components/Cards/Cards.jsx, client/src/components/Header/Header.css, client/src/components/Home/Home.css, client/src/components/tiendaCategorias/categorias/Categorias.jsx, client/src/components/tiendaCategorias/destacados/Destacados.css, client/src/components/tiendaCategorias/destacados/Destacados.jsx, client/src/components/tiendaCategorias/marcas/Marcas.jsx, client/src/data/categorias.js
=> Rutas Front

api/src/data/products.json
A pedido del Lucho para poder hacer el conteo en el carrito
=> Add of QUANTITY in product.json

client/src/App.js, client/src/components/tiendaCategorias/Tienda.jsx, client/src/components/tiendaCategorias/banner/Banner.jsx, client/src/components/tiendaCategorias/destacados/Destacados.css, client/src/components/tiendaCategorias/style.css
cambio de baners mas links agregados
=> baner de shop

client/src/components/Login/Login.jsx, client/src/components/Logout/Logout.jsx, client/src/index.js
=> PRUEBA DEPLOY

api/src/controllers/usersControllers.js, api/src/routes/usersRouter.js, client/src/Redux/actions/index.js, client/src/components/Header/Header.jsx, client/src/components/Manage_Products/Manage_Products.css, client/src/components/Manage_Products/Manage_Products.jsx, client/src/components/Manage_Profiles/Manage_Profiles.jsx
seguimos con dashboard de admin
=> seguimos con dashboard de admin

client/src/App.js, client/src/components/Footers/Footers.css, client/src/components/Footers/Footers.jsx, client/src/components/Home/Form/Form.css
=> mas cambios

api/src/controllers/billsControllers.js, api/src/models/Bills.js, api/src/routes/billsRouter.js, api/src/routes/index.js, client/src/components/OrderConfirmation/OrderConfirmation.jsx
Ya se guarda en la base de datos la factura, me faltaria solo poder traer el idUser del usuario, y poder traer las notificaciones
=> se realiza posteo de la bills

api/src/controllers/billsControllers.js, api/src/data/reviews.json, api/src/db.js, api/src/models/Bills.js, client/src/components/Filter/Filter.jsx, client/src/components/OrderConfirmation/OrderConfirmation.jsx
se realiza todo lo de mercadopago
=> Dev facu frias

api/src/controllers/usersControllers.js, api/src/models/Users.js, client/src/Redux/actions/index.js, client/src/components/Checkout/Checkout.jsx
=> cambios deploy

client/src/components/Card/Card.jsx
=> estilo a la rewiew

api/src/controllers/billsControllers.js, api/src/controllers/productsControllers.js, api/src/controllers/reviewsControllers.js, api/src/models/Bills.js, api/src/routes/productsRouter.js, client/src/Redux/actions/index.js, client/src/components/OrderConfirmation/OrderConfirmation.jsx
se realizan:
1) se agrega la propiedad image a la bills
2) se carga idUser en reviews
3) se carga una nueva ruta para control de stock en el back
=> cambios en la bills, reviews y agregado de ruta para stock

client/src/components/Card/Card.jsx
=> se muestra la reviews

api/src/controllers/usersControllers.js, client/src/components/Profile/Profile.css, client/src/components/Profile/Profile.jsx
y intento de hacer el profile controlado!!!
=> cambios en el back para que quede actualizado

client/src/components/Header/Header.css, client/src/components/Header/Header.jsx, client/src/components/SearchBar/SearchBar.css, client/src/components/SearchBar/SearchBar.jsx, client/src/data/members.js
=> Header arreglado

client/src/Redux/actions/index.js, client/src/components/Manage_Profiles/Manage_Profiles.jsx
=> users disable o no
